# Generated by Django 5.2.14 on 2026-05-16 15:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resourcemanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredRouteConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interface_name', models.CharField(db_index=True, help_text='Linux 接口名，对应 netplan 设备名（如 eth0、wg01）', max_length=128, verbose_name='接口名')),
                ('netplan_device_class', models.CharField(choices=[('ethernets', '物理网卡 (ethernets)'), ('tunnels', '隧道 (tunnels)'), ('bridges', '桥 (bridges)'), ('vlans', 'VLAN (vlans)'), ('bonds', '绑定 (bonds)'), ('wifis', '无线 (wifis)')], db_index=True, default='ethernets', help_text='路由挂载到哪一类设备键下，须与实际 netplan 定义一致以便合并', max_length=32, verbose_name='netplan 设备类型')),
                ('dest_cidr', models.CharField(help_text='CIDR（如 192.168.0.0/24）或 netplan 关键字 default', max_length=128, verbose_name='目标')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='下一跳 (via)')),
                ('on_link', models.BooleanField(default=False, help_text='无网关的直连路由时使用（equivalent to on-link: true）', verbose_name='on-link')),
                ('metric', models.PositiveIntegerField(blank=True, null=True, verbose_name='metric')),
                ('route_table', models.PositiveIntegerField(blank=True, null=True, verbose_name='路由表 table')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_allocation', models.ForeignKey(blank=True, help_text='可选，绑定资源管理中已分配/预留的 IP，用于与接口标识对齐校验', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_intents', to='resourcemanage.ipaddressentry', verbose_name='关联 IP 分配')),
            ],
            options={
                'verbose_name': '路由意图配置',
                'verbose_name_plural': '路由意图配置',
                'ordering': ['interface_name', 'dest_cidr', 'id'],
            },
        ),
    ]
