# Generated by Django 5.2.14 on 2026-05-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacemanage', '0002_desiredtunnelconfig'),
        ('routemanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desiredrouteconfig',
            name='linked_interface',
            field=models.ForeignKey(blank=True, help_text='可选：与「接口数据库镜像」对齐；保存时可由此自动带出接口名与 netplan 设备类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_route_configs', to='interfacemanage.networkinterfacerecord', to_field='ifname', verbose_name='关联接口记录'),
        ),
    ]
