# Generated by Django 5.2.14 on 2026-05-20 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routemanage', '0002_desired_route_linked_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRouteRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='可选，便于识别', max_length=128, verbose_name='名称')),
                ('priority', models.PositiveIntegerField(blank=True, db_index=True, help_text='ip rule priority；建议 10000-19999（pemanager 受控段）', null=True, verbose_name='优先级 priority')),
                ('family', models.CharField(choices=[('inet', 'IPv4 (inet)'), ('inet6', 'IPv6 (inet6)')], db_index=True, default='inet', max_length=8, verbose_name='地址族')),
                ('invert', models.BooleanField(default=False, verbose_name='not (取反)')),
                ('from_cidr', models.CharField(blank=True, max_length=128, verbose_name='源 (from)')),
                ('to_cidr', models.CharField(blank=True, max_length=128, verbose_name='目的 (to)')),
                ('iif', models.CharField(blank=True, max_length=128, verbose_name='入接口 iif')),
                ('oif', models.CharField(blank=True, max_length=128, verbose_name='出接口 oif')),
                ('fwmark', models.CharField(blank=True, help_text='例如 0x1 或 1/0xff', max_length=64, verbose_name='fwmark')),
                ('tos', models.CharField(blank=True, max_length=16, verbose_name='tos')),
                ('suppress_prefixlength', models.PositiveIntegerField(blank=True, null=True, verbose_name='suppress_prefixlength')),
                ('action', models.CharField(choices=[('lookup', '查表 lookup <table>'), ('blackhole', '丢弃 blackhole'), ('unreachable', '不可达 unreachable'), ('prohibit', '禁止 prohibit'), ('nat', 'NAT')], default='lookup', max_length=16, verbose_name='动作')),
                ('table_id', models.PositiveIntegerField(blank=True, help_text='action=lookup 时必填；可填表 ID', null=True, verbose_name='路由表 table')),
                ('nat_target', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='NAT 目标')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '策略路由意图',
                'verbose_name_plural': '策略路由意图',
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['family', 'priority'], name='routemanage_family_3f0c0a_idx')],
            },
        ),
    ]
