# Generated by Django 5.2.14 on 2026-05-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanage', '0002_add_recycled_state'),
        ('routemanage', '0003_policyrouterule'),
    ]

    operations = [
        migrations.AddField(
            model_name='desiredrouteconfig',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='仅用于业务关联与权限作用域，不会写入 netplan / ip route / wg-quick 等系统配置文件', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_route_configs', to='resourcemanage.resourcecustomer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='policyrouterule',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='仅用于业务关联与权限作用域，不会写入 ip rule 等系统配置文件', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_route_rules', to='resourcemanage.resourcecustomer', verbose_name='关联客户'),
        ),
    ]
