# Generated by Django 5.2.14 on 2026-05-19 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('chain', models.CharField(choices=[('input', 'INPUT (本机入向)'), ('output', 'OUTPUT (本机出向)'), ('forward', 'FORWARD (转发)')], db_index=True, max_length=16, verbose_name='链')),
                ('action', models.CharField(choices=[('accept', 'ACCEPT'), ('drop', 'DROP'), ('reject', 'REJECT'), ('log', 'LOG (记录后默认 accept)')], default='accept', max_length=16, verbose_name='动作')),
                ('family', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6'), ('both', 'IPv4 + IPv6')], default='both', max_length=8, verbose_name='协议族')),
                ('protocol', models.CharField(choices=[('any', 'ANY'), ('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP/ICMPv6')], default='any', max_length=8, verbose_name='L4 协议')),
                ('src_cidr', models.CharField(blank=True, max_length=128, verbose_name='源 CIDR')),
                ('dst_cidr', models.CharField(blank=True, max_length=128, verbose_name='目的 CIDR')),
                ('src_port', models.CharField(blank=True, help_text='单个端口/区间(如 22 或 1000-2000)', max_length=64, verbose_name='源端口')),
                ('dst_port', models.CharField(blank=True, max_length=64, verbose_name='目的端口')),
                ('in_interface', models.CharField(blank=True, max_length=128, verbose_name='入接口')),
                ('out_interface', models.CharField(blank=True, max_length=128, verbose_name='出接口')),
                ('priority', models.IntegerField(default=100, help_text='数值小者优先；同链内按 (priority, created_at) 排序生成规则', verbose_name='优先级')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '防火墙规则',
                'verbose_name_plural': '防火墙规则',
                'ordering': ['chain', 'priority', 'created_at'],
            },
        ),
    ]
