# Generated by Django 5.2.14 on 2026-05-21 02:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewallmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(choices=[('nft', 'nftables (nft)'), ('iptables', 'iptables (iptables-restore)')], default='nft', max_length=16, verbose_name='引擎')),
                ('policy_input', models.CharField(choices=[('accept', 'ACCEPT'), ('drop', 'DROP')], default='accept', max_length=8, verbose_name='默认 input 策略')),
                ('policy_output', models.CharField(choices=[('accept', 'ACCEPT'), ('drop', 'DROP')], default='accept', max_length=8, verbose_name='默认 output 策略')),
                ('policy_forward', models.CharField(choices=[('accept', 'ACCEPT'), ('drop', 'DROP')], default='accept', max_length=8, verbose_name='默认 forward 策略')),
                ('last_apply_at', models.DateTimeField(blank=True, null=True, verbose_name='最近下发时间')),
                ('last_apply_ok', models.BooleanField(default=False, verbose_name='最近下发是否成功')),
                ('last_apply_summary', models.CharField(blank=True, max_length=512, verbose_name='最近下发摘要')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '防火墙设置',
                'verbose_name_plural': '防火墙设置',
            },
        ),
        migrations.CreateModel(
            name='NATRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('kind', models.CharField(choices=[('dnat', 'DNAT (目标地址转换)'), ('snat', 'SNAT (源地址转换)'), ('masquerade', 'MASQUERADE (动态源 NAT)'), ('redirect', 'REDIRECT (重定向本机端口)')], db_index=True, max_length=16, verbose_name='类型')),
                ('family', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], default='ipv4', max_length=8, verbose_name='协议族')),
                ('protocol', models.CharField(choices=[('any', 'ANY'), ('tcp', 'TCP'), ('udp', 'UDP')], default='any', max_length=8, verbose_name='L4 协议')),
                ('in_interface', models.CharField(blank=True, max_length=128, verbose_name='入接口 (iifname)')),
                ('out_interface', models.CharField(blank=True, max_length=128, verbose_name='出接口 (oifname)')),
                ('src_cidr', models.CharField(blank=True, max_length=128, verbose_name='源 CIDR')),
                ('dst_cidr', models.CharField(blank=True, max_length=128, verbose_name='目的 CIDR')),
                ('dst_port', models.CharField(blank=True, help_text='单个端口或 1000-2000', max_length=64, verbose_name='目的端口')),
                ('to_ip', models.CharField(blank=True, help_text='DNAT/SNAT 必填', max_length=128, verbose_name='目标 IP')),
                ('to_port', models.CharField(blank=True, help_text='DNAT/REDIRECT 选填；端口或 1000-2000', max_length=64, verbose_name='目标端口')),
                ('priority', models.IntegerField(default=100, help_text='数值小者优先', verbose_name='优先级')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NAT 规则',
                'verbose_name_plural': 'NAT 规则',
                'ordering': ['kind', 'priority', 'created_at'],
            },
        ),
    ]
