"""
将 DesiredRouteConfig 写入 netplan 路由片段并执行 netplan generate / netplan try。
复用 interfacemanage 的 netplan 命令前缀、子进程与超时策略。
"""
from __future__ import annotations

from typing import Any, Literal

import yaml
from django.conf import settings

from interfacemanage.services.netplan_writing import _run, _write_netplan_file
from routemanage.models import DesiredRouteConfig

ApplyPhase = Literal['full', 'validate', 'try']


def build_route_network() -> dict[str, Any]:
    """按 netplan 设备类与接口名聚合 routes 列表。"""
    grouped: dict[str, dict[str, dict[str, Any]]] = {}

    for obj in DesiredRouteConfig.objects.all().order_by('interface_name', 'dest_cidr', 'id'):
        dclass = obj.netplan_device_class
        ifname = (obj.interface_name or '').strip()
        if not ifname:
            continue
        dest = (obj.dest_cidr or '').strip()
        if not dest:
            continue
        if dclass not in grouped:
            grouped[dclass] = {}
        if ifname not in grouped[dclass]:
            grouped[dclass][ifname] = {'routes': []}

        entry: dict[str, Any] = {'to': dest}
        if obj.gateway:
            entry['via'] = str(obj.gateway)
        if obj.on_link:
            entry['on-link'] = True
        if obj.metric is not None:
            entry['metric'] = int(obj.metric)
        if obj.route_table is not None:
            entry['table'] = int(obj.route_table)
        grouped[dclass][ifname]['routes'].append(entry)

    network: dict[str, Any] = {'version': 2}
    for dclass, devices in grouped.items():
        if devices:
            network[dclass] = devices
    return network


def render_route_fragment_yaml() -> str:
    return yaml.safe_dump(
        {'network': build_route_network()},
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
    )


def preview_desired_routes_yaml() -> dict[str, Any]:
    """仅生成将要写入片段的 YAML，不写磁盘、不调用 netplan。"""
    try:
        body = render_route_fragment_yaml()
        return {'ok': True, 'yaml': body}
    except Exception as exc:  # noqa: BLE001
        return {'ok': False, 'error': f'生成路由 YAML 失败: {exc}'}


def apply_desired_routes_netplan(*, phase: ApplyPhase | str = 'full') -> dict[str, Any]:
    """
    phase:
    - validate: 写入片段 + netplan generate（校验合并配置）
    - try: 仅 netplan try（依赖磁盘上已是上一轮 validate 写入的片段）
    - full: 写入 + generate + try
    """
    phase_l = (phase or 'full').lower()
    if phase_l not in {'full', 'validate', 'try'}:
        return {'ok': False, 'error': f'未知 phase: {phase!r}，可选 full / validate / try', 'steps': []}

    if not getattr(settings, 'ROUTEMANAGE_NETPLAN_WRITE_ENABLED', False):
        return {
            'ok': False,
            'error': '路由 netplan 写入已关闭（settings.ROUTEMANAGE_NETPLAN_WRITE_ENABLED）',
            'steps': [],
        }

    path = str(
        getattr(
            settings,
            'ROUTEMANAGE_NETPLAN_FRAGMENT_FILE',
            '/etc/netplan/99-pemanager-routes.yaml',
        )
    )
    steps: list[dict[str, Any]] = []
    body = ''

    try:
        body = render_route_fragment_yaml()
    except Exception as exc:  # noqa: BLE001
        return {'ok': False, 'error': f'生成路由 YAML 失败: {exc}', 'steps': steps}

    if phase_l in {'full', 'validate'}:
        try:
            _write_netplan_file(
                path,
                '# Generated by PE Manager — desired static routes\n',
                body,
            )
            steps.append({'step': 'write routes fragment', 'path': path, 'ok': True})
        except OSError as exc:
            steps.append({'step': 'write routes fragment', 'path': path, 'ok': False, 'stderr': str(exc)})
            return {'ok': False, 'error': f'写入 {path} 失败: {exc}', 'steps': steps, 'yaml_preview': body}

        gen = _run(['netplan', 'generate'], timeout_kind='apply')
        steps.append(
            {
                'step': 'netplan generate',
                'ok': gen.ok,
                'returncode': gen.returncode,
                'stderr': gen.stderr,
                'stdout': gen.stdout,
            }
        )
        if not gen.ok:
            return {
                'ok': False,
                'error': 'netplan generate 失败',
                'steps': steps,
                'yaml_preview': body,
            }

        if phase_l == 'validate':
            return {'ok': True, 'phase': 'validate', 'steps': steps, 'yaml_preview': body}

    try_timeout = int(getattr(settings, 'ROUTEMANAGE_NETPLAN_TRY_TIMEOUT', 120))
    try_timeout = max(10, min(try_timeout, 600))

    try_res = _run(
        ['netplan', 'try', '--timeout', str(try_timeout)],
        input_text='\n',
        timeout_kind='apply',
    )
    steps.append(
        {
            'step': 'netplan try',
            'ok': try_res.ok,
            'returncode': try_res.returncode,
            'stderr': try_res.stderr,
            'stdout': try_res.stdout,
            'timeout_sec': try_timeout,
        }
    )

    if try_res.ok:
        return {'ok': True, 'phase': phase_l, 'steps': steps, 'yaml_preview': body}

    return {
        'ok': False,
        'error': 'netplan try 失败或超时；已尝试回滚（以 netplan 行为为准）',
        'steps': steps,
        'yaml_preview': body,
    }
