# Generated by Django 5.2.14 on 2026-05-16 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('total_mbps', models.PositiveIntegerField(verbose_name='总带宽(Mbps)')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '带宽池',
                'verbose_name_plural': '带宽池',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAllocationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('action', models.CharField(choices=[('ip_reserve', 'IP 预留'), ('ip_allocate', 'IP 分配'), ('ip_release', 'IP 释放'), ('ip_update', 'IP 变更'), ('bw_create', '带宽分配创建'), ('bw_update', '带宽分配变更'), ('bw_delete', '带宽分配删除'), ('sync_outbound', '同步下发(资源→其他应用)'), ('sync_inbound', '同步回写(其他应用→资源)')], db_index=True, max_length=32, verbose_name='操作')),
                ('actor', models.CharField(blank=True, help_text='用户名或 system / api', max_length=128, verbose_name='操作者')),
                ('summary', models.CharField(max_length=512, verbose_name='摘要')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='明细')),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='关联追踪')),
            ],
            options={
                'verbose_name': '资源操作日志',
                'verbose_name_plural': '资源操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='客户编码')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IPAddressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP 地址')),
                ('state', models.CharField(choices=[('available', '可用'), ('reserved', '预留'), ('allocated', '已分配')], db_index=True, default='available', max_length=16, verbose_name='状态')),
                ('subnet_label', models.CharField(blank=True, help_text='用于标识地址段或 VLAN 等，便于过滤', max_length=128, verbose_name='网段/分组标签')),
                ('interface_code', models.CharField(blank=True, db_index=True, help_text='与 interfacemanage 等模块约定的接口编码，便于同步下发', max_length=128, verbose_name='接口标识')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='resourcemanage.resourcecustomer', verbose_name='客户')),
            ],
            options={
                'verbose_name': 'IP 地址',
                'verbose_name_plural': 'IP 地址',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='BandwidthAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_code', models.CharField(db_index=True, help_text='与业务模块约定的接口编码', max_length=128, verbose_name='接口标识')),
                ('allocated_mbps', models.PositiveIntegerField(verbose_name='分配带宽(Mbps)')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='resourcemanage.bandwidthpool', verbose_name='带宽池')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandwidth_allocations', to='resourcemanage.resourcecustomer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '带宽分配',
                'verbose_name_plural': '带宽分配',
                'ordering': ['pool', 'interface_code'],
                'constraints': [models.UniqueConstraint(fields=('pool', 'interface_code'), name='uniq_bandwidth_pool_interface')],
            },
        ),
    ]
