# Generated by Django 5.2.14 on 2026-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressentry',
            name='state',
            field=models.CharField(choices=[('available', '可用'), ('reserved', '预留'), ('allocated', '已分配'), ('recycled', '回收（不可分配）')], db_index=True, default='available', max_length=16, verbose_name='状态'),
        ),
    ]
