# Generated by Django 5.2.14 on 2026-05-19 03:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('address', models.CharField(help_text='IPv4/IPv6/主机名', max_length=255, verbose_name='目标地址')),
                ('kind', models.CharField(choices=[('ping', 'Ping (ICMP)'), ('mtr', 'MTR')], db_index=True, default='ping', max_length=16, verbose_name='类型')),
                ('interval_sec', models.PositiveIntegerField(default=60, verbose_name='采样间隔(秒)')),
                ('count', models.PositiveSmallIntegerField(default=5, verbose_name='单次报文数')),
                ('source_interface', models.CharField(blank=True, max_length=128, verbose_name='源接口(可选)')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sampled_at', models.DateTimeField(blank=True, null=True, verbose_name='最后采样')),
            ],
            options={
                'verbose_name': '监控目标',
                'verbose_name_plural': '监控目标',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceTrafficSample',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interface_name', models.CharField(db_index=True, max_length=128, verbose_name='接口')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('rx_bytes_total', models.BigIntegerField(default=0, verbose_name='累计 RX bytes')),
                ('tx_bytes_total', models.BigIntegerField(default=0, verbose_name='累计 TX bytes')),
                ('rx_packets_total', models.BigIntegerField(default=0, verbose_name='累计 RX 包')),
                ('tx_packets_total', models.BigIntegerField(default=0, verbose_name='累计 TX 包')),
                ('rx_bps', models.FloatField(blank=True, null=True, verbose_name='RX bps（窗口）')),
                ('tx_bps', models.FloatField(blank=True, null=True, verbose_name='TX bps（窗口）')),
                ('window_sec', models.FloatField(blank=True, null=True, verbose_name='窗口(秒)')),
            ],
            options={
                'verbose_name': '接口流量样本',
                'verbose_name_plural': '接口流量样本',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['interface_name', '-ts'], name='operationma_interfa_45f1dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='LatencySample',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('rtt_min_ms', models.FloatField(blank=True, null=True, verbose_name='RTT min(ms)')),
                ('rtt_avg_ms', models.FloatField(blank=True, null=True, verbose_name='RTT avg(ms)')),
                ('rtt_max_ms', models.FloatField(blank=True, null=True, verbose_name='RTT max(ms)')),
                ('jitter_ms', models.FloatField(blank=True, null=True, verbose_name='抖动(ms)')),
                ('loss_pct', models.FloatField(blank=True, null=True, verbose_name='丢包率(%)')),
                ('packets_sent', models.PositiveIntegerField(default=0, verbose_name='发送')),
                ('packets_recv', models.PositiveIntegerField(default=0, verbose_name='接收')),
                ('ok', models.BooleanField(db_index=True, default=True, verbose_name='采样成功')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='明细')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latency_samples', to='operationmanage.monitortarget', verbose_name='目标')),
            ],
            options={
                'verbose_name': '延迟样本',
                'verbose_name_plural': '延迟样本',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['target', '-ts'], name='operationma_target__cee0eb_idx')],
            },
        ),
    ]
