# Generated by Django 5.2.14 on 2026-05-21 03:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticsJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ping', 'Ping'), ('mtr', 'MTR')], db_index=True, max_length=8, verbose_name='类型')),
                ('address', models.CharField(max_length=255, verbose_name='目标地址')),
                ('source', models.CharField(blank=True, max_length=128, verbose_name='源 IP / 接口')),
                ('count', models.PositiveIntegerField(default=10, verbose_name='报文数')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('succeeded', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='queued', max_length=16, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='结果')),
                ('error', models.TextField(blank=True, verbose_name='错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '诊断任务',
                'verbose_name_plural': '诊断任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interface_name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='接口')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('interval_sec', models.PositiveIntegerField(default=15, verbose_name='采样间隔(秒)')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sampled_at', models.DateTimeField(blank=True, null=True, verbose_name='最后采样')),
            ],
            options={
                'verbose_name': '接口流量监控对象',
                'verbose_name_plural': '接口流量监控对象',
                'ordering': ['interface_name'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceTrafficRollup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interface_name', models.CharField(db_index=True, max_length=128, verbose_name='接口')),
                ('bucket_kind', models.CharField(choices=[('minute', '分钟'), ('hour', '小时'), ('day', '天')], db_index=True, max_length=8, verbose_name='粒度')),
                ('bucket_ts', models.DateTimeField(db_index=True, verbose_name='桶起点')),
                ('rx_bps_avg', models.FloatField(blank=True, null=True, verbose_name='RX 平均 bps')),
                ('rx_bps_max', models.FloatField(blank=True, null=True, verbose_name='RX 峰值 bps')),
                ('tx_bps_avg', models.FloatField(blank=True, null=True, verbose_name='TX 平均 bps')),
                ('tx_bps_max', models.FloatField(blank=True, null=True, verbose_name='TX 峰值 bps')),
                ('rx_bytes_delta', models.BigIntegerField(default=0, verbose_name='RX 增量 bytes')),
                ('tx_bytes_delta', models.BigIntegerField(default=0, verbose_name='TX 增量 bytes')),
                ('samples', models.PositiveIntegerField(default=0, verbose_name='样本数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '接口流量汇总',
                'verbose_name_plural': '接口流量汇总',
                'ordering': ['-bucket_ts'],
                'indexes': [models.Index(fields=['interface_name', 'bucket_kind', '-bucket_ts'], name='operationma_interfa_5af30a_idx')],
                'constraints': [models.UniqueConstraint(fields=('interface_name', 'bucket_kind', 'bucket_ts'), name='uniq_traffic_rollup_iface_bucket')],
            },
        ),
        migrations.CreateModel(
            name='LatencyRollup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bucket_kind', models.CharField(choices=[('minute', '分钟'), ('hour', '小时'), ('day', '天')], db_index=True, max_length=8, verbose_name='粒度')),
                ('bucket_ts', models.DateTimeField(db_index=True, verbose_name='桶起点')),
                ('rtt_min_ms', models.FloatField(blank=True, null=True, verbose_name='RTT min(ms)')),
                ('rtt_avg_ms', models.FloatField(blank=True, null=True, verbose_name='RTT avg(ms)')),
                ('rtt_max_ms', models.FloatField(blank=True, null=True, verbose_name='RTT max(ms)')),
                ('jitter_ms', models.FloatField(blank=True, null=True, verbose_name='抖动(ms)')),
                ('loss_pct', models.FloatField(blank=True, null=True, verbose_name='丢包率(%)')),
                ('samples', models.PositiveIntegerField(default=0, verbose_name='样本数')),
                ('ok_samples', models.PositiveIntegerField(default=0, verbose_name='成功样本')),
                ('packets_sent', models.PositiveIntegerField(default=0, verbose_name='发送')),
                ('packets_recv', models.PositiveIntegerField(default=0, verbose_name='接收')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latency_rollups', to='operationmanage.monitortarget', verbose_name='目标')),
            ],
            options={
                'verbose_name': '延迟汇总',
                'verbose_name_plural': '延迟汇总',
                'ordering': ['-bucket_ts'],
                'indexes': [models.Index(fields=['target', 'bucket_kind', '-bucket_ts'], name='operationma_target__5d8098_idx')],
                'constraints': [models.UniqueConstraint(fields=('target', 'bucket_kind', 'bucket_ts'), name='uniq_latency_rollup_target_bucket')],
            },
        ),
    ]
