# Generated by Django 5.2.14 on 2026-05-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationmanage', '0002_add_diagnostics_job'),
        ('resourcemanage', '0002_add_recycled_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorinterface',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='仅用于业务关联与权限作用域；客户账号只能看到自己客户名下接口的监控对象', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_interfaces', to='resourcemanage.resourcecustomer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='仅用于业务关联与权限作用域；客户账号只能看到所属客户的监控目标', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_targets', to='resourcemanage.resourcecustomer', verbose_name='关联客户'),
        ),
    ]
