# Generated by Django 5.2.14 on 2026-05-16 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='统计')),
            ],
            options={
                'verbose_name': '网络配置同步任务',
                'verbose_name_plural': '网络配置同步任务',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkInterfaceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifname', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='接口名')),
                ('ifindex', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ifindex')),
                ('kind', models.CharField(db_index=True, max_length=64, verbose_name='类型')),
                ('admin_up', models.BooleanField(blank=True, null=True, verbose_name='管理 UP')),
                ('operstate', models.CharField(blank=True, max_length=32, verbose_name='运行状态')),
                ('mtu', models.PositiveIntegerField(blank=True, null=True, verbose_name='MTU')),
                ('mac', models.CharField(blank=True, max_length=64, verbose_name='MAC')),
                ('addresses', models.JSONField(blank=True, default=list, verbose_name='地址(ip -json addr 子树)')),
                ('linkinfo', models.JSONField(blank=True, default=dict, verbose_name='linkinfo')),
                ('netplan', models.JSONField(blank=True, null=True, verbose_name='Netplan 对齐信息')),
                ('wireguard', models.JSONField(blank=True, null=True, verbose_name='WireGuard 快照')),
                ('ip_tunnel_show', models.JSONField(blank=True, null=True, verbose_name='ip tunnel show 解析')),
                ('unified', models.JSONField(blank=True, default=dict, verbose_name='合并行(完整)')),
                ('content_sha256', models.CharField(db_index=True, max_length=64, verbose_name='内容校验')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='首次出现')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='最近见到')),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces', to='interfacemanage.networksyncrun', verbose_name='最近同步任务')),
            ],
            options={
                'verbose_name': '网络接口记录',
                'verbose_name_plural': '网络接口记录',
                'ordering': ['ifindex', 'ifname'],
            },
        ),
        migrations.CreateModel(
            name='NetplanFileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=512, unique=True, verbose_name='文件路径')),
                ('file_sha256', models.CharField(db_index=True, max_length=64, verbose_name='文件 SHA-256')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='字节数')),
                ('mtime_epoch', models.FloatField(blank=True, null=True, verbose_name='mtime(秒)')),
                ('raw_yaml', models.TextField(blank=True, verbose_name='原始 YAML')),
                ('parsed', models.JSONField(blank=True, default=dict, verbose_name='解析结果')),
                ('parse_error', models.TextField(blank=True, verbose_name='解析错误')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netplan_files', to='interfacemanage.networksyncrun', verbose_name='最近同步任务')),
            ],
            options={
                'verbose_name': 'Netplan 文件快照',
                'verbose_name_plural': 'Netplan 文件快照',
                'ordering': ['path'],
            },
        ),
    ]
