# Generated by Django 5.2.14 on 2026-05-16 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacemanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredTunnelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('gre', 'GRE'), ('vxlan', 'VXLAN'), ('wireguard', 'WireGuard')], db_index=True, max_length=32, verbose_name='类型')),
                ('ifname', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='接口名')),
                ('spec', models.JSONField(blank=True, default=dict, help_text='与 netplan / wg 对齐的结构化字段', verbose_name='配置载荷')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '隧道接口意图配置',
                'verbose_name_plural': '隧道接口意图配置',
                'ordering': ['kind', 'ifname'],
            },
        ),
    ]
