# Generated by Django 5.2.14 on 2026-05-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacemanage', '0002_desiredtunnelconfig'),
        ('resourcemanage', '0002_add_recycled_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='desiredtunnelconfig',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='仅用于业务关联与权限作用域，不会写入 netplan/wg-quick 等系统配置文件', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_tunnel_configs', to='resourcemanage.resourcecustomer', verbose_name='关联客户'),
        ),
    ]
