# Generated by Django 5.2.14 on 2026-05-19 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppOperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('app', models.CharField(db_index=True, max_length=64, verbose_name='应用')),
                ('category', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='类别')),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR')], db_index=True, default='info', max_length=16, verbose_name='级别')),
                ('actor', models.CharField(blank=True, max_length=128, verbose_name='操作者')),
                ('summary', models.CharField(max_length=512, verbose_name='摘要')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='明细')),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='关联追踪')),
                ('target', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='对象标识')),
            ],
            options={
                'verbose_name': '应用操作日志',
                'verbose_name_plural': '应用操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
