"""根据 FirewallRule 渲染 nftables 规则集，并支持预览 / 写入 / 应用。"""
from __future__ import annotations

import ipaddress
import os
import shlex
import tempfile
from datetime import datetime
from typing import Any, Iterable, Literal

from django.conf import settings

from firewallmanage.models import FirewallRule
from interfacemanage.services import subprocess_util

Phase = Literal['preview', 'validate', 'apply', 'flush']

TABLE_NAME = 'pemanager'
CHAIN_HOOKS = {
    FirewallRule.Chain.INPUT: ('input', 'filter', 0),
    FirewallRule.Chain.OUTPUT: ('output', 'filter', 0),
    FirewallRule.Chain.FORWARD: ('forward', 'filter', 0),
}


def _cmd_prefix() -> list[str]:
    raw = getattr(settings, 'FIREWALLMANAGE_CMD_PREFIX', '')
    if isinstance(raw, list):
        return list(raw)
    if isinstance(raw, str) and raw.strip():
        return shlex.split(raw)
    return []


def _family_keyword(cidr: str) -> str:
    try:
        net = ipaddress.ip_network(cidr.strip(), strict=False)
        return 'ip6' if net.version == 6 else 'ip'
    except ValueError:
        return 'ip'


def _port_expr(port: str) -> str:
    if '-' in port:
        a, b = port.split('-', 1)
        return f'{int(a)}-{int(b)}'
    return str(int(port))


def _rule_lines_for_family(rule: FirewallRule, family: str) -> list[str]:
    """family: 'ip' or 'ip6'。"""
    parts: list[str] = []
    if rule.in_interface:
        parts.append(f'iifname "{rule.in_interface}"')
    if rule.out_interface:
        parts.append(f'oifname "{rule.out_interface}"')

    if rule.src_cidr:
        net = ipaddress.ip_network(rule.src_cidr.strip(), strict=False)
        if (net.version == 6) == (family == 'ip6'):
            parts.append(f'{family} saddr {net}')
        else:
            return []
    if rule.dst_cidr:
        net = ipaddress.ip_network(rule.dst_cidr.strip(), strict=False)
        if (net.version == 6) == (family == 'ip6'):
            parts.append(f'{family} daddr {net}')
        else:
            return []

    if rule.protocol == FirewallRule.Protocol.TCP:
        parts.append('tcp')
        if rule.src_port:
            parts.append(f'sport {_port_expr(rule.src_port)}')
        if rule.dst_port:
            parts.append(f'dport {_port_expr(rule.dst_port)}')
    elif rule.protocol == FirewallRule.Protocol.UDP:
        parts.append('udp')
        if rule.src_port:
            parts.append(f'sport {_port_expr(rule.src_port)}')
        if rule.dst_port:
            parts.append(f'dport {_port_expr(rule.dst_port)}')
    elif rule.protocol == FirewallRule.Protocol.ICMP:
        parts.append('icmpv6' if family == 'ip6' else 'icmp')

    if rule.action == FirewallRule.Action.ACCEPT:
        verdict = 'accept'
    elif rule.action == FirewallRule.Action.DROP:
        verdict = 'drop'
    elif rule.action == FirewallRule.Action.REJECT:
        verdict = 'reject'
    else:  # LOG => log + accept
        verdict = f'log prefix "pemanager:{rule.name[:24]}" accept'

    comment = ''
    if rule.remark or rule.name:
        c = (rule.remark or rule.name).replace('"', "'")[:60]
        comment = f' comment "{c}"'

    return [' '.join(parts + [verdict]).strip() + comment]


def _expand_rule_to_families(rule: FirewallRule) -> Iterable[tuple[str, str]]:
    """yield (family, line)"""
    targets: list[str] = []
    if rule.family == FirewallRule.Family.IPV4:
        targets = ['ip']
    elif rule.family == FirewallRule.Family.IPV6:
        targets = ['ip6']
    else:
        targets = ['ip', 'ip6']

    for fam in targets:
        for ln in _rule_lines_for_family(rule, fam):
            if ln:
                yield (fam, ln)


def render_ruleset() -> str:
    """构造 inet 表 + 三条 chain + 已启用规则。"""
    out: list[str] = []
    out.append(f'# Generated by PE Manager at {datetime.utcnow().isoformat()}Z')
    out.append(f'table inet {TABLE_NAME} {{')
    out.append('  chain input    { type filter hook input    priority 0; policy accept; }')
    out.append('  chain output   { type filter hook output   priority 0; policy accept; }')
    out.append('  chain forward  { type filter hook forward  priority 0; policy accept; }')
    out.append('}')

    chain_to_lines: dict[str, list[str]] = {'input': [], 'output': [], 'forward': []}
    qs = FirewallRule.objects.filter(enabled=True).order_by('chain', 'priority', 'created_at')
    for rule in qs:
        chain = rule.chain
        for _fam, ln in _expand_rule_to_families(rule):
            chain_to_lines[chain].append(ln)

    out.append('')
    out.append(f'flush chain inet {TABLE_NAME} input')
    out.append(f'flush chain inet {TABLE_NAME} output')
    out.append(f'flush chain inet {TABLE_NAME} forward')

    for chain in ('input', 'output', 'forward'):
        for ln in chain_to_lines[chain]:
            out.append(f'add rule inet {TABLE_NAME} {chain} {ln}')

    return '\n'.join(out) + '\n'


def _run_nft(args: list[str], *, timeout: int = 10):
    return subprocess_util.run(_cmd_prefix() + ['nft'] + args, timeout=timeout)


def _write_temp_ruleset(text: str) -> str:
    fd, path = tempfile.mkstemp(prefix='pemanager-fw-', suffix='.nft')
    with os.fdopen(fd, 'w', encoding='utf-8') as f:
        f.write(text)
    return path


def apply_ruleset(*, phase: Phase = 'apply') -> dict[str, Any]:
    if phase == 'preview':
        return {'ok': True, 'phase': phase, 'ruleset': render_ruleset()}

    if not getattr(settings, 'FIREWALLMANAGE_APPLY_ENABLED', False):
        return {
            'ok': False,
            'error': '防火墙下发已关闭（settings.FIREWALLMANAGE_APPLY_ENABLED）',
            'steps': [],
            'ruleset': render_ruleset(),
        }

    ruleset = render_ruleset()
    steps: list[dict[str, Any]] = []

    if phase == 'flush':
        for ch in ('input', 'output', 'forward'):
            r = _run_nft(['flush', 'chain', 'inet', TABLE_NAME, ch])
            steps.append({'step': f'flush {ch}', 'ok': r.ok, 'stderr': r.stderr, 'stdout': r.stdout})
        return {'ok': all(s['ok'] for s in steps), 'phase': 'flush', 'steps': steps}

    tmp_path = _write_temp_ruleset(ruleset)
    steps.append({'step': 'write ruleset', 'ok': True, 'path': tmp_path})

    chk = _run_nft(['-c', '-f', tmp_path])
    steps.append({'step': 'nft -c (check)', 'ok': chk.ok, 'stderr': chk.stderr, 'stdout': chk.stdout})
    if not chk.ok:
        return {'ok': False, 'error': 'nft -c 校验失败', 'steps': steps, 'ruleset': ruleset}

    if phase == 'validate':
        return {'ok': True, 'phase': 'validate', 'steps': steps, 'ruleset': ruleset}

    app = _run_nft(['-f', tmp_path])
    steps.append({'step': 'nft -f (apply)', 'ok': app.ok, 'stderr': app.stderr, 'stdout': app.stdout})
    if not app.ok:
        return {'ok': False, 'error': 'nft -f 应用失败', 'steps': steps, 'ruleset': ruleset}

    return {'ok': True, 'phase': 'apply', 'steps': steps, 'ruleset': ruleset}


def show_ruleset() -> dict[str, Any]:
    r = _run_nft(['list', 'table', 'inet', TABLE_NAME])
    return {
        'ok': r.ok,
        'exit_code': r.exit_code,
        'stderr': r.stderr,
        'stdout': r.stdout,
    }
