# Generated by Django 5.2.14 on 2026-05-19 03:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QoSPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('interface_name', models.CharField(db_index=True, help_text='Linux ifname (eth0, wg0...)', max_length=128, verbose_name='接口名')),
                ('direction', models.CharField(choices=[('egress', '出向 (egress)'), ('ingress', '入向 (ingress / IFB)')], default='egress', max_length=16, verbose_name='方向')),
                ('root_kind', models.CharField(choices=[('htb', 'HTB (分级限速)'), ('fq_codel', 'fq_codel (公平队列)'), ('cake', 'CAKE (智能调度)')], default='htb', max_length=16, verbose_name='根 qdisc')),
                ('default_rate_mbps', models.PositiveIntegerField(default=100, verbose_name='默认带宽(Mbps)')),
                ('default_ceil_mbps', models.PositiveIntegerField(default=100, verbose_name='默认峰值(Mbps)')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QoS 策略',
                'verbose_name_plural': 'QoS 策略',
                'ordering': ['interface_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QoSRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_id', models.PositiveSmallIntegerField(help_text='HTB 类的 minor 号（>=10 推荐），同策略内唯一', verbose_name='类 ID (minor)')),
                ('rate_mbps', models.PositiveIntegerField(verbose_name='保证带宽(Mbps)')),
                ('ceil_mbps', models.PositiveIntegerField(verbose_name='峰值带宽(Mbps)')),
                ('priority', models.PositiveSmallIntegerField(default=4, verbose_name='优先级 (1-7)')),
                ('match_kind', models.CharField(choices=[('src', '源 CIDR'), ('dst', '目的 CIDR'), ('dscp', 'DSCP'), ('any', '任意')], default='dst', max_length=8, verbose_name='匹配字段')),
                ('match_value', models.CharField(blank=True, help_text='CIDR 或 DSCP，留空=any', max_length=128, verbose_name='匹配值')),
                ('remark', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='qosmanage.qospolicy', verbose_name='策略')),
            ],
            options={
                'verbose_name': 'QoS 规则 (HTB 类)',
                'verbose_name_plural': 'QoS 规则 (HTB 类)',
                'ordering': ['policy', 'priority', 'class_id'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'class_id'), name='uniq_qos_policy_classid')],
            },
        ),
    ]
