# Generated by Django 5.2.14 on 2026-05-21 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacemanage', '0002_desiredtunnelconfig'),
        ('qosmanage', '0001_initial'),
        ('resourcemanage', '0002_add_recycled_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='qospolicy',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='可选，QoS 策略归属的客户；用于资源管理 / 接口详情联动展示', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qos_policies', to='resourcemanage.resourcecustomer', verbose_name='所属客户'),
        ),
        migrations.AddField(
            model_name='qospolicy',
            name='linked_interface',
            field=models.ForeignKey(blank=True, help_text='可选，绑定接口数据库镜像（与 interface_name 自动保持一致）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qos_policies', to='interfacemanage.networkinterfacerecord', to_field='ifname', verbose_name='关联接口记录'),
        ),
        migrations.AddField(
            model_name='qospolicy',
            name='linked_pool',
            field=models.ForeignKey(blank=True, help_text='可选；若指定，保存策略时会自动在该池中 upsert 一条 BandwidthAllocation（pool, interface_name）= default_ceil_mbps，使资源管理实时可见', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qos_policies', to='resourcemanage.bandwidthpool', verbose_name='关联带宽池'),
        ),
        migrations.AddField(
            model_name='qospolicy',
            name='synced_bandwidth_allocation',
            field=models.ForeignKey(blank=True, help_text='由 QoS 同步逻辑写入；策略删除时一并清理', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qos_origin', to='resourcemanage.bandwidthallocation', verbose_name='已同步的带宽分配'),
        ),
    ]
