# Generated by Django 5.2.14 on 2026-05-21 01:50

from django.db import migrations, models


def backfill_rate_and_kind(apps, schema_editor):
    """把老字段 default_ceil_mbps 回填到新字段 rate_mbps；
    把已废弃的 fq_codel / cake 模板统一切到 htb（单类限速）。"""
    Policy = apps.get_model('qosmanage', 'QoSPolicy')
    for p in Policy.objects.all():
        ceil = int(getattr(p, 'default_ceil_mbps', 0) or 0)
        if ceil > 0:
            p.rate_mbps = ceil
        if p.root_kind not in ('htb', 'tbf'):
            p.root_kind = 'htb'
        p.save(update_fields=['rate_mbps', 'root_kind'])


def noop_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('qosmanage', '0002_link_customer_pool_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='qospolicy',
            name='burst_kb',
            field=models.PositiveSmallIntegerField(default=32, help_text='TBF 令牌桶大小，太小会卡顿；约为速率的 1/100 ~ 1/50', verbose_name='TBF burst (KB)'),
        ),
        migrations.AddField(
            model_name='qospolicy',
            name='headroom_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='为应对突发与协议开销，从限速中预留的百分比；实际下发 = rate × (100 - headroom) / 100', verbose_name='冗余度 (%)'),
        ),
        migrations.AddField(
            model_name='qospolicy',
            name='latency_ms',
            field=models.PositiveSmallIntegerField(default=50, help_text='TBF 队列里超过该延迟的包将被丢弃', verbose_name='TBF 最大延迟 (ms)'),
        ),
        migrations.AddField(
            model_name='qospolicy',
            name='rate_mbps',
            field=models.PositiveIntegerField(default=10, help_text='接口总限速；保存后会同步到资源管理的带宽分配', verbose_name='限速 (Mbps)'),
        ),
        migrations.AlterField(
            model_name='qospolicy',
            name='default_ceil_mbps',
            field=models.PositiveIntegerField(default=10, verbose_name='保留: default_ceil_mbps'),
        ),
        migrations.AlterField(
            model_name='qospolicy',
            name='default_rate_mbps',
            field=models.PositiveIntegerField(default=10, verbose_name='保留: default_rate_mbps'),
        ),
        migrations.AlterField(
            model_name='qospolicy',
            name='root_kind',
            field=models.CharField(choices=[('htb', 'HTB 单类限速 (推荐：HTB+fq_codel)'), ('tbf', 'TBF 极简硬限速 (Token Bucket)')], default='htb', max_length=16, verbose_name='限速模板'),
        ),
        migrations.RunPython(backfill_rate_and_kind, noop_backwards),
    ]
